FROM ubuntu:latest

ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt clean
RUN apt autoclean
RUN apt-get -y update
RUN cd ~

COPY . node-chat-app/
WORKDIR node-chat-app

